### ISSUE TITLE
NFT already is listed error

### ISSUE THREAD

**Issue by pickacrowd** [maximedrn/opensea-automatic-bulk-upload-and-sale#381]
I installed the latest release on a new machine and trying to list (No3 sale only) already uploaded nfts with your tools. I get the "NFT Already is listed" error. Also I found chromedriver blocks all the images on opensea, not sure about the issues.
![listed](https://user-images.githubusercontent.com/67396205/193954742-53630600-d089-44c4-9559-a16c347c4b7c.jpg)

**Comment by TBack12** [comment]
idem

**Comment by TBack12** [comment]
Problem when entering properties it crashes

**Comment by maximedrn** [comment]
I released the patch for these 2 issues!

**Comment by pickacrowd** [comment]
I installed a fresh copy after you release the patches but the problem is not solved yet. This time it opens the listing pages but not filling the details, please see the attached screencast video.
https://user-images.githubusercontent.com/67396205/194124305-198472a7-87f8-4a72-a7d1-620a32730725.mp4

**Comment by maximedrn** [comment]
Fixed, sorry for this mistake with the URL.

**Comment by pickacrowd** [comment]
Resolved the issue. Thank you so much!
